Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,46 +1,80 @@
-name: Visual Reports
+name: visual reports
 
 on:
   pull_request:
     types: [opened, synchronize, reopened]
-
-jobs:
-  test-and-report:
-    runs-on: self-hosted
     
+jobs:
+  lint-and-test:
+    runs-on: self-hosted
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Install Python
+        run: |
+          sudo apt install -y python3 python3-pip
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: '3.x'  # Choose your Python version here
-
+          python-version: '3.x'
+          
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r requirements.txt  # Install project dependencies including pytest and coverage
-
-      - name: Run tests and generate coverage report
+          pip install -r requirements.txt
+      - name: Run Flake8
+        id: flake8
+        run: |
+          flake8 src --output-file=flake8-result.txt || true
+      - name: Set PYTHONPATH
+        run: |
+          export PYTHONPATH=$PYTHONPATH:$(pwd)/src:$(pwd)/tests
+      - name: Run tests
         run: |
           mkdir -p reports/unit
           mkdir -p reports/coverage
-          python -m pytest tests --cov=src --cov-report xml:reports/coverage/coverage.xml --junitxml=reports/unit/unit.xml
+          python -m pytest tests --cov=. --cov-report xml:reports/coverage/coverage.xml --junitxml=reports/unit/unit.xml
         continue-on-error: true
 
-      - name: Upload test and coverage reports
+      - name: Upload test results
         uses: actions/upload-artifact@v2
         with:
-          name: test-coverage-reports
-          path: |
-            reports/unit
-            reports/coverage
-
-      - name: Publish Test Results as PR Comment
-        if: always()  # Ensure this step runs even if previous steps fail
-        uses: mikepenz/action-junit-report@v4
+          name: test-results
+          path: reports/unit/unit.xml
+          
+      - name: Upload lint results
+        uses: actions/upload-artifact@v2
         with:
-          report_paths: ./reports/unit/unit.xml
-          github_token: ${{ secrets.MY_GITHUB_PAT }}
+          name: lint-results
+          path: flake8-result.txt
 
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v2
+        with:
+          name: coverage-report
+          path: reports/coverage/coverage.xml
+
+      - name: Test Reports
+        uses: xportation/junit-coverage-report@main
+        with:
+          junit-path: reports/unit/unit.xml  
+          coverage-path: reports/coverage/coverage.xml
+
+      - name: Create comment with test and coverage results
+        if: github.event_name == 'pull_request'
+        uses: xportation/junit-coverage-report@main
+        with:
+          junit-path: reports/unit/unit.xml
+          coverage-path: reports/coverage/coverage.xml
+          github-token: ${{ secrets.MY_GITHUB_PAT }}
+          
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: reports/unit/unit.xml
+          check_name: 'Unit Test Results'
+          fail_on_failure: false
+          require_tests: true
